# Set allowlist to `false` to allow anyone; otherwise add entries such as "@user:example.com"
allowlist: []
default_backend: "local"
tools:
  enabled_tools: ["react", "fetch_url", "get_current_datetime"]
  debug_messages: false

backends:
  local:
    type: basic_openai
    base_url: "http://localhost:1234"
    authorization: null
    default_model: null
    default_system_prompt: "You are helpful digital assistant. You are participating in a multi-user chat room. Only answer when directly addressed, otherwise write '-'."
